{% set name = "sklearn-genetic-opt" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 05826e6a0183dc0a11ec343bfdc0b06c01899aca44df422e8a72ccb0ad93b60a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - deap >=1.3.3
    - mlflow >=1.17.0
    - numpy >=1.19.0
    - python >={{ python_min }}
    - scikit-learn >=1.1.0
    - seaborn >=0.11.2
    - tensorflow >=2.0.0
    - tqdm >=4.61.1

test:
  imports:
    - sklearn_genetic
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rodrigo-arenas/Sklearn-genetic-opt
  summary: Scikit-lean models hyperparameters tuning, using evolutionary algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - rodrigo-arenas
